SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR, (B.MAXI - A.SIZE_OF_COLONY) AS YEAR_DEV, A.ID
FROM ECOLI_DATA AS A
JOIN
(
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAXI
FROM ECOLI_DATA
GROUP BY YEAR(DIFFERENTIATION_DATE)
)
AS B ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC
