SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE "2022-08-01" <= START_DATE AND START_DATE <= "2022-10-31" AND CAR_ID IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE "2022-08-01" <= START_DATE AND START_DATE <= "2022-10-31" GROUP BY CAR_ID HAVING COUNT(HISTORY_ID) >= 5)
GROUP BY CAR_ID, MONTH(START_DATE)
HAVING RECORDS > 0
ORDER BY MONTH(START_DATE) ASC, CAR_ID DESC
