SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(C.SALES*B.PRICE) AS TOTAL_SALES
FROM BOOK_SALES AS C
INNER JOIN BOOK AS B ON C.BOOK_ID = B.BOOK_ID
INNER JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE YEAR(C.SALES_DATE)=2022 AND MONTH(C.SALES_DATE)=1
GROUP BY CATEGORY, AUTHOR_ID
ORDER BY A.AUTHOR_ID, CATEGORY DESC
