SELECT A.CATEGORY, SUM(BOOK_SALES) AS TOTAL_SALES
FROM BOOK AS A
INNER JOIN (
SELECT BOOK_ID, SUBSTR(SALES_DATE, 1, 7) AS SALES_DATE, SUM(SALES) AS BOOK_SALES
FROM BOOK_SALES
WHERE SUBSTR(SALES_DATE, 1, 7) = "2022-01"
GROUP BY BOOK_ID, SUBSTR(SALES_DATE, 1, 7)
) AS B ON A.BOOK_ID = B.BOOK_ID
GROUP BY A.CATEGORY
ORDER BY A.CATEGORY ASC
